# Generated by Django 4.2.28 on 2026-03-05 03:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_id', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Número do Pedido')),
                ('origin', models.CharField(choices=[('table', 'Mesa'), ('delivery', 'Delivery'), ('counter', 'Balcão')], default='table', max_length=20, verbose_name='Origem')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('preparing', 'Preparando'), ('ready', 'Pronto'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='new', max_length=20, verbose_name='Status')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tables.table', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço no momento do pedido', max_digits=10, verbose_name='Preço unitário')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.menuitem', verbose_name='Item do Cardápio')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'db_table': 'order_items',
            },
        ),
    ]
