# Generated by Django 4.2.28 on 2026-03-05 03:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefone')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Pontos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cartão Fidelidade',
                'verbose_name_plural': 'Cartões Fidelidade',
                'db_table': 'loyalty_cards',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('points_required', models.PositiveIntegerField(verbose_name='Pontos necessários')),
                ('emoji', models.CharField(default='🎁', max_length=10, verbose_name='Emoji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Recompensa',
                'verbose_name_plural': 'Recompensas',
                'db_table': 'loyalty_rewards',
                'ordering': ['points_required', 'display_order'],
            },
        ),
    ]
