# Generated by Django 4.2.28 on 2026-03-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='RestoPro', max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('instagram', models.CharField(blank=True, default='', max_length=100, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, default='', max_length=100, verbose_name='Facebook')),
                ('website', models.CharField(blank=True, default='', max_length=200, verbose_name='Website')),
                ('address_street', models.CharField(blank=True, default='', max_length=300, verbose_name='Rua / Endereço')),
                ('address_city', models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade')),
                ('address_state', models.CharField(blank=True, default='', max_length=2, verbose_name='Estado')),
                ('address_zip', models.CharField(blank=True, default='', max_length=10, verbose_name='CEP')),
                ('parking_available', models.BooleanField(default=False, verbose_name='Estacionamento disponível')),
                ('opening_hours', models.JSONField(blank=True, default=dict, verbose_name='Horário de funcionamento')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Informações do Restaurante',
                'verbose_name_plural': 'Informações do Restaurante',
                'db_table': 'restaurant_info',
            },
        ),
    ]
