# Generated by Django 4.2.28 on 2026-03-05 03:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('acknowledged', 'Atendido')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_calls', to='tables.table', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Chamada de Garçom',
                'verbose_name_plural': 'Chamadas de Garçom',
                'db_table': 'waiter_calls',
                'ordering': ['-created_at'],
            },
        ),
    ]
