# Generated by Django 4.2.28 on 2026-03-05 03:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Número')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='Capacidade')),
                ('status', models.CharField(choices=[('free', 'Livre'), ('occupied', 'Ocupada'), ('reserved', 'Reservada'), ('cleaning', 'Aguardando Limpeza')], default='free', max_length=20, verbose_name='Status')),
                ('occupied_by', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pessoas sentadas')),
                ('reservation_time', models.TimeField(blank=True, null=True, verbose_name='Horário da reserva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'db_table': 'tables',
                'ordering': ['number'],
            },
        ),
    ]
