# Generated by Django 4.2.28 on 2026-03-05 03:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcquirerConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acquirer_type', models.CharField(choices=[('mercadopago', 'Mercado Pago'), ('pagbank', 'PagBank'), ('infinitepay', 'InfinitePay'), ('pagarme', 'Pagar.me')], max_length=20, unique=True, verbose_name='Adquirente')),
                ('access_token', models.CharField(max_length=500, verbose_name='Access Token')),
                ('public_key', models.CharField(blank=True, default='', max_length=500, verbose_name='Public Key')),
                ('pix_enabled', models.BooleanField(default=True, verbose_name='Pix habilitado')),
                ('credit_enabled', models.BooleanField(default=True, verbose_name='Crédito habilitado')),
                ('debit_enabled', models.BooleanField(default=True, verbose_name='Débito habilitado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adquirente',
                'verbose_name_plural': 'Adquirentes',
                'db_table': 'acquirer_configs',
            },
        ),
    ]
