# Generated by Django 4.2.28 on 2026-04-18 18:42

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=menu.models.menu_image_upload, verbose_name='Imagem'),
        ),
    ]
