# Generated by Django 4.2.28 on 2026-02-26 13:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Imagem')),
                ('emoji', models.CharField(blank=True, default='🍽️', max_length=10, verbose_name='Emoji')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('low_stock', 'Pouco Estoque'), ('out_of_stock', 'Esgotado')], default='available', max_length=20, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Item do Cardápio',
                'verbose_name_plural': 'Itens do Cardápio',
                'db_table': 'menu_items',
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_id', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Número do Pedido')),
                ('origin', models.CharField(choices=[('table', 'Mesa'), ('delivery', 'Delivery'), ('counter', 'Balcão')], default='table', max_length=20, verbose_name='Origem')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('preparing', 'Preparando'), ('ready', 'Pronto'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado')], default='new', max_length=20, verbose_name='Status')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Número')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='Capacidade')),
                ('status', models.CharField(choices=[('free', 'Livre'), ('occupied', 'Ocupada'), ('reserved', 'Reservada'), ('cleaning', 'Aguardando Limpeza')], default='free', max_length=20, verbose_name='Status')),
                ('occupied_by', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pessoas sentadas')),
                ('reservation_time', models.TimeField(blank=True, null=True, verbose_name='Horário da reserva')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'db_table': 'tables',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='WaiterCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('acknowledged', 'Atendido')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_calls', to='core.table', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Chamada de Garçom',
                'verbose_name_plural': 'Chamadas de Garçom',
                'db_table': 'waiter_calls',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço no momento do pedido', max_digits=10, verbose_name='Preço unitário')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.menuitem', verbose_name='Item do Cardápio')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
                'db_table': 'order_items',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.table', verbose_name='Mesa'),
        ),
    ]
